### PR TITLE
Display more information about deployment based on description

### PR DESCRIPTION
**Pull request by benoittgt**
As mentioned in [Github documentation](https://docs.github.com/en/rest/deployments/deployments#about-the-deployments-api):
> Deployment statuses can also include an optional description and log_url, which are highly recommended because they make deployment statuses more useful.

We want to avoid having duplicate information between "pipeline" and "deployments" and use the more rich informations provided on description.

d-11-10_à_15_11_10

For people who use the classic Github Action to mark deployment as suggested by Jira. It's here:

https://github.com/chrnorm/deployment-action/blob/880668c419e283adc6b1cc092d52eb5e558fec4d/action.yml#L24-L26

Related:
  - https://github.com/atlassian/github-for-jira/issues/1536
  - https://github.com/atlassian/github-for-jira/pull/1732
  - https://github.com/atlassian/github-for-jira/pull/1736

### CODE REVIEW

**Comment by benoittgt** [comment]
For the test. This is pure guessing. I was not able to run the test locally.

**Comment by rachellerathbone** [comment]
@benoittgt there are several checks failing. Could you please resolve this and we can work on getting this merged.

**Comment by benoittgt** [comment]
Sorry that's an old work. I didn't have time yet to look at it.

**Comment by benoittgt** [comment]
I have no time to work on this ATM.

**Pull request closed without merging**
