### PR TITLE
ARC-408: Remove runOnce from staging and prod

### PR DESCRIPTION
**Pull request by atrigueiro**
Do not merge until the [changes](https://bitbucket.org/atlassian/github-for-jira-deployment/pull-requests/39/arc-408-run-pollinator-after-stg-deploy) to the pipeline are merged.

### CODE REVIEW

**Review by joshkay10 — DISMISSED** [review]
🤌

**Comment by Harminder84** [comment]
runOnce for prod is there.  Can we run PDV for prod in same way as we're doing for staging?

**Comment by gxueatlassian** [comment]
> runOnce for prod is there. Can we run PDV for prod in same way as we're doing for staging?

Agree, I like the idea of removing the runOnce (due to flaky) here at all, but run it in the pipeline.

**Review by gxueatlassian — DISMISSED** [review]

**Review by gxueatlassian — APPROVED** [review]

**Review by Harminder84 — APPROVED** [review]

**Comment by bgvozdev** [comment]
:killitwithfire:

**Comment by bgvozdev** [comment]
> Do not merge until the [changes](https://bitbucket.org/atlassian/github-for-jira-deployment/pull-requests/39/arc-408-run-pollinator-after-stg-deploy) to the pipeline are merged.

IMHO not a big deal because it is kinda useless anyway: the UI is still served by the old stack and SQS will be picked by the old stack with 50% chance...

**Pull request merged**
