### PR TITLE
Track stats for total commits pushed and commits with jira issue key

### PR DESCRIPTION
**Pull request by endeepak**
**What's in this PR?**
Sends an analytic event to track the total commits pushed and number of commits containing the jira issue key in the commit message.

I'm not sure if such an event is useful for the backfilled commits.

**Why**
Context: We are planning to associate commits to services in Jira Service Management(JSM) most probably via deployment association to services. This will help JSM users to find the root cause fast during incident investigation.

Reason: We need stats on percentage of commits not stored in Open Toolchain due to lack of jira issue keys in the commit message. This stat will help us decide if we should plan additional work to store commits without issue keys in the future. 

**Added feature flags**
None.

**Affected issues**  
None. This was discussed in Atlassian slack: https://atlassian.slack.com/archives/CFG3W7TKJ/p1673239842789059

**How has this been tested?** 
I've tested the following cases on local using debugger:
1. Push a commit with jira issue key.
2. Push a commit without jira issue key.
3. Push multiple commits where only one of them contains issue key.

I couldn't test it end-to-end on local because analytic events are not sent to any source in a non-prod environment. Appreciate any help in testing this end-to-end before merging to prod.

**Whats Next?**
* I need to register this event in Atlassian event registry.
* I may request a similar change for BitBucket integration as well.
* Analyse the data for 2+ weeks to make the decision mentioned above.

### CODE REVIEW

**Review by rachellerathbone — DISMISSED** [review]
Looks good to me. Not sure how much experience you have registering events but might be worth reading our how to guide, particularly [this section](https://hello.atlassian.net/wiki/spaces/OTFS/pages/1836204793/HOWTO+Find+and+Create+Analytics#Some-things-to-be-aware-of). As long as you follow that, you won't have any issues seeing your event in Amplitude.

**Comment by Harminder84** [comment]
@endeepak, please fix the linitng errors.

**Comment by endeepak** [comment]
Thanks @Harminder84 I've fixed the lint error. I've also updated the contribution doc to run a command which runs both lint and build.

@rachellerathbone Thanks for reviewing the PR. The doc you have shared is very useful. This is my first time registering an event in the event registry. I will follow the instructions. I'm planning to enable only Amplitude as a consumer of this event to start with. Should I enable it for any other consumers such as Socrates?

**Review by Harminder84 — APPROVED** [review]

**Comment by endeepak** [comment]
@Harminder84 Thanks for approving. The E2E test is failing for this PR. I tried running the same command on local. It errored for few missing env vars. Is there any doc for E2E test setup on local I can follow?

I noticed similar failure for another PR for minor version update: https://github.com/atlassian/github-for-jira/pull/1824/files. Are the E2E tests reliable? Is there a way to re-rerun the tests as per this https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs? 
(I couldn't find the button to re-run with my login. Maybe permission issue or the github plan used by this repo)

**Comment by Harminder84** [comment]
> @Harminder84 Thanks for approving. The E2E test is failing for this PR. I tried running the same command on local. It errored for few missing env vars. Is there any doc for E2E test setup on local I can follow?
> 
> I noticed similar failure for another PR for minor version update: https://github.com/atlassian/github-for-jira/pull/1824/files. Are the E2E tests reliable? Is there a way to re-rerun the tests as per this https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs? (I couldn't find the button to re-run with my login. Seems to be due to my permissions)

@endeepak , E2E tests are optional at the moment. More work require for an externl source PR. You can igonre E2E check as of now.

**Comment by endeepak** [comment]
@Harminder84 Thanks for the clarification. The "Merge pull request" button is disabled due to e2e test failure. What are the next steps to merge this Pull request?

**Comment by Harminder84** [comment]
> @Harminder84 Thanks for the clarification. The "Merge pull request" button is disabled probably due to e2e test failure or my permissions. What are the next steps to merge this Pull request?

@endeepak I merged the PR on your behalf.

**Pull request merged**
