### PR TITLE
ARC-753 use JWT Authentication for /github/login endpoint

### PR DESCRIPTION
**Pull request by KAbakumovAtl**
Added JWT Authentication for /github/login endpoint and save Jira Hostname to the session.

This should solve https://github.com/atlassian/github-for-jira/issues/868 yet keeping the installation flow secure

### CODE REVIEW

**Comment by KAbakumovAtl** [comment]
According to the review from the security team. The solution is good enough. Sean tried it in ddev and was satisfied with the results.

**Comment by KAbakumovAtl** [comment]
Discarding this PR, because we figured out that we use **login** function in multiple places already, so we can't assume that we'll have Jira hostname and token in it every time it is called. So we need ot separate setting Jira Hostname from login. 

Hence fixing this PR it will require a lot of job already, we better implement a proper solution.
1. Stop using `/github/login` endpoint for "Add Github Organisation" button. Use /github/configure instead.
2. Change /github/configure to make it do the following:
  a. Check Jira JWT Token, set JiraHostname to the session. 
  b. Check if we have GitHub Auth Token in the context, call "login" function if we don't have it

**Comment by pat-bao** [comment]
Hi @KAbakumovAtl, is there currently any workaround to adding a GitHub Organisation? We're attempting to link Jira to GitHub but currently we just get errors. Will we need to wait until the 'proper solution' is implemented? Thanks.

**Comment by mboudreau** [comment]
@pat-bao if you enable 3rd party cookies in your browsers and refresh the landing page, it'll work

**Pull request closed without merging**
