### PR TITLE
Provide an url when possible on deployment environment section

### PR DESCRIPTION
**Pull request by benoittgt**
We want to be able to easily access to an environment when possible from the deployment page.

Capdture_d’écran_2022-11-10_à_15_11_10

It needs to be provided as environment_url when making deployment status call. https://docs.github.com/en/rest/deployments/statuses#create-a-deployment-status

For people who use the classic Github Action to mark deployment as suggested by Jira. It's here:

https://github.com/chrnorm/deployment-action/blob/880668c419e283adc6b1cc092d52eb5e558fec4d/action.yml#L31-L33

Related:
  - https://github.com/atlassian/github-for-jira/issues/1536
  - https://github.com/atlassian/github-for-jira/pull/1732

### CODE REVIEW

**Comment by benoittgt** [comment]
For the test. This is pure guessing. It was not super friendly to run it locally.

**Comment by rachellerathbone** [comment]
@benoittgt there are several checks failing. Could you please resolve this and we can work on getting this merged.

**Comment by aldenquimby** [comment]
@rachellerathbone noting my PR was closed b/c the Jira API doesn't support URLs on the environment object. I imagine that means this PR should be closed too?

**Comment by benoittgt** [comment]
That's sad :/

**Pull request closed without merging**
